export type UserStatus = "Active" | "Pending invite" | "Deactivated" | "Locked" | "Suspended";

const teamValues = [
  "Platform",
  "Growth",
  "Revenue",
  "Customer Ops",
  "Internal Tools",
  "Compliance",
  "People Ops",
  "Finance",
] as const;

export type UserTeam = (typeof teamValues)[number];

export type UserRow = {
  email: string;
  joinedDate: string;
  lastActive: number;
  name: string;
  role: string;
  status: UserStatus;
  team: UserTeam;
  workspace: string[];
};

export const users: UserRow[] = [
  {
    name: "Ahmad Farhan bin Zulkifli",
    email: "farhan.zulkifli@company.com",
    role: "Workspace Owner",
    status: "Active",
    team: "Platform",
    workspace: ["HQ Main", "Internal Tools"],
    joinedDate: "24 Jun 2024, 9:23 AM",
    lastActive: 0,
  },
  {
    name: "Mohd Hafiz bin Razak",
    email: "hafiz.razak@company.com",
    role: "Admin",
    status: "Active",
    team: "Growth",
    workspace: ["HQ Main"],
    joinedDate: "15 Mar 2023, 2:45 PM",
    lastActive: 5,
  },
  {
    name: "Nurul Izzah binti Hashim",
    email: "nurul.izzah@company.com",
    role: "Billing Admin",
    status: "Active",
    team: "Revenue",
    workspace: ["HQ Main"],
    joinedDate: "10 Apr 2022, 11:30 AM",
    lastActive: 14 * 24 * 60,
  },
  {
    name: "Khairul Anuar bin Mansor",
    email: "khairul.anuar@company.com",
    role: "Security Admin",
    status: "Locked",
    team: "Internal Tools",
    workspace: ["HQ Main", "Internal Tools"],
    joinedDate: "28 Feb 2023, 6:15 PM",
    lastActive: 60,
  },
  {
    name: "Siti Aishah binti Radzi",
    email: "siti.aishah@company.com",
    role: "Team Lead",
    status: "Active",
    team: "Customer Ops",
    workspace: ["HQ Main"],
    joinedDate: "19 May 2024, 7:55 AM",
    lastActive: 2 * 60,
  },
  {
    name: "Muhammad Danial bin Azman",
    email: "danial.azman@company.com",
    role: "Contributor",
    status: "Pending invite",
    team: "Compliance",
    workspace: ["HQ Main"],
    joinedDate: "03 Jan 2024, 12:05 PM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Nur Fatihah binti Kamaruddin",
    email: "fatihah.k@company.com",
    role: "Guest",
    status: "Active",
    team: "Internal Tools",
    workspace: ["Internal Tools"],
    joinedDate: "21 Jul 2023, 8:40 PM",
    lastActive: 3 * 60,
  },
  {
    name: "Zulhilmi bin Shamsuddin",
    email: "zulhilmi.s@company.com",
    role: "Read-only",
    status: "Deactivated",
    team: "Revenue",
    workspace: ["HQ Main"],
    joinedDate: "16 Sep 2023, 3:25 PM",
    lastActive: 6,
  },
  {
    name: "Amirul Asyraf bin Ismail",
    email: "amirul.asyraf@company.com",
    role: "Contributor",
    status: "Active",
    team: "People Ops",
    workspace: ["HQ Main", "Internal Tools"],
    joinedDate: "04 Nov 2022, 9:50 AM",
    lastActive: 12,
  },
  {
    name: "Farah Nadia binti Othman",
    email: "farah.nadia@company.com",
    role: "Admin",
    status: "Active",
    team: "Platform",
    workspace: ["HQ Main"],
    joinedDate: "30 Dec 2023, 4:35 PM",
    lastActive: 30,
  },
  {
    name: "Haris bin Abdullah",
    email: "haris.abdullah@company.com",
    role: "Team Lead",
    status: "Suspended",
    team: "Internal Tools",
    workspace: ["Internal Tools"],
    joinedDate: "12 Feb 2024, 10:20 AM",
    lastActive: 8 * 24 * 60,
  },
  {
    name: "Ainul Mardhiah binti Yahya",
    email: "ainul.mardhiah@company.com",
    role: "Contributor",
    status: "Active",
    team: "Growth",
    workspace: ["HQ Main"],
    joinedDate: "08 Aug 2023, 1:10 PM",
    lastActive: 24 * 60,
  },
  {
    name: "Syazwan bin Rosli",
    email: "syazwan.rosli@company.com",
    role: "Guest",
    status: "Pending invite",
    team: "Customer Ops",
    workspace: ["HQ Main"],
    joinedDate: "17 Jan 2024, 5:45 PM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Nabilah binti Abdul Rahman",
    email: "nabilah.ar@company.com",
    role: "Billing Admin",
    status: "Active",
    team: "Finance",
    workspace: ["HQ Main"],
    joinedDate: "02 Oct 2023, 11:15 AM",
    lastActive: 45,
  },
  {
    name: "Irfan Hakim bin Salleh",
    email: "irfan.hakim@company.com",
    role: "Security Admin",
    status: "Active",
    team: "Internal Tools",
    workspace: ["HQ Main", "Internal Tools"],
    joinedDate: "22 May 2024, 8:30 AM",
    lastActive: 10,
  },
  {
    name: "Anis Sofea binti Mahadir",
    email: "anis.sofea@company.com",
    role: "Read-only",
    status: "Active",
    team: "Compliance",
    workspace: ["Internal Tools"],
    joinedDate: "14 Jul 2023, 6:05 PM",
    lastActive: 4 * 60,
  },
  {
    name: "Haziq bin Mustaffa",
    email: "haziq.mustaffa@company.com",
    role: "Contributor",
    status: "Deactivated",
    team: "Platform",
    workspace: ["HQ Main"],
    joinedDate: "26 Nov 2022, 3:40 PM",
    lastActive: 21 * 24 * 60,
  },
  {
    name: "Puteri Balqis binti Mokhtar",
    email: "puteri.balqis@company.com",
    role: "Team Lead",
    status: "Active",
    team: "Revenue",
    workspace: ["HQ Main"],
    joinedDate: "11 Apr 2024, 9:05 AM",
    lastActive: 18,
  },
  {
    name: "Luqman Al-Hakim bin Zainal",
    email: "luqman.zainal@company.com",
    role: "Guest",
    status: "Locked",
    team: "Growth",
    workspace: ["HQ Main"],
    joinedDate: "09 Sep 2023, 12:25 PM",
    lastActive: 2 * 24 * 60,
  },
  {
    name: "Nur Syuhada binti Bakar",
    email: "syuhada.bakar@company.com",
    role: "Admin",
    status: "Active",
    team: "Internal Tools",
    workspace: ["HQ Main", "Internal Tools"],
    joinedDate: "05 Dec 2023, 2:15 PM",
    lastActive: 0,
  },
  {
    name: "Zulkifli bin Daud",
    email: "zulkifli.daud@company.com",
    role: "Contributor",
    status: "Active",
    team: "Platform",
    workspace: ["HQ Main"],
    joinedDate: "18 Jun 2024, 4:50 PM",
    lastActive: 7,
  },
];

export const filters = {
  role: [
    "All",
    "Workspace Owner",
    "Admin",
    "Billing Admin",
    "Security Admin",
    "Team Lead",
    "Contributor",
    "Guest",
    "Read-only",
  ],
  team: ["All", ...teamValues],
  status: ["All", "Active", "Pending invite", "Deactivated", "Locked", "Suspended"],
  workspace: ["All", "HQ Main", "Internal Tools"],
};

export const statusMeta: Record<UserStatus, { badgeClass: string; dotClass: string }> = {
  Active: {
    badgeClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    dotClass: "bg-emerald-500",
  },
  "Pending invite": {
    badgeClass: "border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-400",
    dotClass: "bg-amber-500",
  },
  Deactivated: {
    badgeClass: "border-border bg-muted/50 text-muted-foreground",
    dotClass: "bg-muted-foreground",
  },
  Locked: {
    badgeClass: "border-destructive/20 bg-destructive/10 text-destructive",
    dotClass: "bg-destructive",
  },
  Suspended: {
    badgeClass: "border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-400",
    dotClass: "bg-orange-500",
  },
};
